name: call-a-workflow-with-params
on: [workflow_dispatch]
jobs:
  call-a-workflow-with-params:
    uses: tst-mgmt/action-test/.github/workflows/workflow-5-reusable-with-params.yml@main
    with:
      some-input: Some input param from calling workflow.
